# Generated by Django 2.1.1 on 2018-09-21 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeeScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_dfe_id', models.PositiveIntegerField()),
                ('fee_setting', models.CharField(max_length=100)),
                ('fee_per_hour', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='FundingStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funding_type', models.CharField(max_length=3)),
                ('funding_weeks', models.PositiveSmallIntegerField()),
                ('funding_min_dob', models.DateField()),
                ('funding_max_dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_name', models.CharField(max_length=50)),
                ('term_start_date', models.DateField()),
                ('term_end_date', models.DateField()),
                ('collection_date', models.DateField()),
                ('dob_min_date', models.DateField()),
                ('dob_max_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='fundingstream',
            name='funding_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Term'),
        ),
        migrations.AddField(
            model_name='feescale',
            name='fee_funding_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.FundingStream'),
        ),
    ]
